site_name: 'Deberes de Gabriel'
theme:
  name: 'material'
  custom_dir: 'overrides'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'
extra_css:
  - 'overrides/extra.css'
nav:
  - Inici: index.md
  - Articles EDD:
    - Article 1: edd/document1.md
    - Article 2: edd/document2.md
    - Article 3: edd/document3.md
    - Article 4: edd/document4.md
    - Article 5: edd/document5.md
    - Article 6: edd/document6.md
  - Articles LMI:
    - Article 1: lmi/document1.md
    - Article 2: lmi/document2.md
